server:
  port: 8080

grpc:
  server:
    port: 9090
    reflection-service-enabled: true

spring:
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    clickhouse.home.event: DEBUG

clickhouse:
  url: http://localhost:8123
  username: default
  password:
  database: playground
